nav:
  Home: /
  About: /#about
  Archives: /archives/
  Projects: /#demos

projects_url: http://github.com/dmkcode

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/dmkcode_images/avatar.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicons/favicon.ico
        gravatar: false
      android:
        url: /images/favicons/android-chrome-192x192.png
        gravator: false
      apple:
        url: /images/favicons/apple-touch-icon.png
        gravator: false
    social_links:
        github: http://github.com/dmkcode
        twitter: https://twitter.com/DMKCode
        linkedin: https://www.linkedin.com/in/davidkananda/
    show_all_posts: false
    post_count: 5
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: DMKCode # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
